<?php

namespace App\Enums;

use Nasyrov\Laravel\Enums\Enum;

class PermissionsEnum extends Enum
{
    // ENABLE_ADMIN_PAGE
    const ENABLE_ADMIN_USERS_MENU = "ENABLE_ADMIN_USERS_MENU";
    const ENABLE_ADMIN_PERMISSIONS_MENU = "ENABLE_ADMIN_PERMISSIONS_MENU";
    const ENABLE_ADMIN_BOOKING_MENU = 'ENABLE_ADMIN_BOOKING_MENU';
    const ENABLE_ADMIN_SETTINGS_MENU = "ENABLE_ADMIN_SETTINGS_MENU";
    const ENABLE_ADMIN_PAGES_MENU = "ENABLE_ADMIN_PAGES_MENU";
    const ENABLE_ADMIN_MENUS_MENU = "ENABLE_ADMIN_MENUS_MENU";
    const ENABLE_ADMIN_SERVICES_MENU = "ENABLE_ADMIN_SERVICES_MENU";
    const ENABLE_ADMIN_BOOKING_CALENDAR_MENU = 'ENABLE_ADMIN_BOOKING_CALENDAR_MENU';
    const ENABLE_ADMIN_BOOKING_DAILY_LIST_MENU = 'ENABLE_ADMIN_BOOKING_DAILY_LIST_MENU';
    const ENABLE_ADMIN_BOOKING_LIST_MENU = 'ENABLE_ADMIN_BOOKING_LIST_MENU';
    const ENABLE_ADMIN_BOOKING_SETTINGS_MENU = 'ENABLE_ADMIN_BOOKING_SETTINGS_MENU';
}
